package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

const samplePR = `diff --git a/cmd/togi/main.go b/cmd/togi/main.go
index 1111111..2222222 100644
--- a/cmd/togi/main.go
+++ b/cmd/togi/main.go
@@ -10,3 +10,4 @@ func main() {
 	a()
-	b()
+	b2()
+	c()
 	d()
@@ -40,2 +41,3 @@ func other() {
 	x()
+	y()
 	z()
diff --git a/go.sum b/go.sum
index 3333333..4444444 100644
--- a/go.sum
+++ b/go.sum
@@ -1,2 +1,3 @@
 a
+b
 c
diff --git a/internal/old.go b/internal/old.go
deleted file mode 100644
index 5555555..0000000
--- a/internal/old.go
+++ /dev/null
@@ -1,2 +0,0 @@
-package internal
-var x = 1
diff --git a/docs/one.md b/docs/two.md
similarity index 80%
rename from docs/one.md
rename to docs/two.md
index 6666666..7777777 100644
--- a/docs/one.md
+++ b/docs/two.md
@@ -1,2 +1,2 @@
 title
-old
+new
diff --git a/logo.png b/logo.png
new file mode 100644
index 0000000..8888888
Binary files /dev/null and b/logo.png differ
diff --git a/pkg/testdata/in.txt b/pkg/testdata/in.txt
new file mode 100644
index 0000000..9999999
--- /dev/null
+++ b/pkg/testdata/in.txt
@@ -0,0 +1 @@
+hello
diff --git a/pkg/gen.go b/pkg/gen.go
new file mode 100644
index 0000000..aaaaaaa
--- /dev/null
+++ b/pkg/gen.go
@@ -0,0 +1,2 @@
+// Code generated by tool; DO NOT EDIT.
+package pkg
diff --git a/pkg/empty b/pkg/empty
new file mode 100644
index 0000000..e69de29
`

func TestParseDiff(t *testing.T) {
	t.Parallel()
	files, err := parseDiff(samplePR)
	if err != nil {
		t.Fatal(err)
	}
	type row struct {
		Path, Old, Status string
		Added, Removed    int
		Binary            bool
		Changed           []span
		Exclusion         string
	}
	var got []row
	for _, f := range files {
		got = append(got, row{f.Path, f.OldPath, f.Status, f.Added, f.Removed, f.Binary, f.Changed, excludedReason(f)})
	}
	want := []row{
		{Path: "cmd/togi/main.go", Status: "modified", Added: 3, Removed: 1, Changed: []span{{11, 12}, {42, 42}}},
		{Path: "go.sum", Status: "modified", Added: 1, Changed: []span{{2, 2}}, Exclusion: "generated"},
		{Path: "internal/old.go", Status: "deleted", Removed: 2},
		{Path: "docs/two.md", Old: "docs/one.md", Status: "renamed", Added: 1, Removed: 1, Changed: []span{{2, 2}}},
		{Path: "logo.png", Status: "added", Binary: true, Exclusion: "binary"},
		{Path: "pkg/testdata/in.txt", Status: "added", Added: 1, Changed: []span{{1, 1}}, Exclusion: "test data (`**/testdata/**`)"},
		{Path: "pkg/gen.go", Status: "added", Added: 2, Changed: []span{{1, 2}}, Exclusion: "generated"},
		{Path: "pkg/empty", Status: "added"},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("files (-want +got):\n%s", diff)
	}
	var joined strings.Builder
	for _, f := range files {
		joined.WriteString(f.Text)
	}
	if joined.String() != samplePR {
		t.Error("the sections do not add up to the input byte for byte")
	}
}

func TestParseDiffEdges(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name, in, wantPath, wantErr string
	}{
		{name: "empty", in: ""},
		{name: "error text", in: "GraphQL: Could not resolve to a PullRequest\n", wantErr: "not a unified diff"},
		{name: "tab after a path with spaces", in: "diff --git a/my file b/my file\n--- a/my file\t\n+++ b/my file\t\n@@ -1 +1 @@\n-a\n+b\n", wantPath: "my file"},
		{name: "mode change", in: "diff --git a/run.sh b/run.sh\nold mode 100644\nnew mode 100755\n", wantPath: "run.sh"},
		{name: "unreadable header", in: "diff --git a/x b/y\nindex 1..2\n", wantErr: "cannot read the path"},
		{name: "no newline marker", in: "diff --git a/f b/f\n--- a/f\n+++ b/f\n@@ -1 +1 @@\n-a\n\\ No newline at end of file\n+b\n\\ No newline at end of file\n", wantPath: "f"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			files, err := parseDiff(tt.in)
			switch {
			case tt.wantErr != "":
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("error = %v, want one containing %q", err, tt.wantErr)
				}
			case err != nil:
				t.Fatal(err)
			case tt.wantPath == "":
				if len(files) != 0 {
					t.Fatalf("got %d files, want none", len(files))
				}
			case len(files) != 1 || files[0].Path != tt.wantPath:
				t.Fatalf("files = %+v, want one at %q", files, tt.wantPath)
			}
		})
	}
}

func TestSameChanges(t *testing.T) {
	t.Parallel()
	patch := func(context, added string) []fileDiff {
		files, err := parseDiff("diff --git a/f b/f\n--- a/f\n+++ b/f\n@@ -5,3 +5,3 @@\n " + context + "\n-old\n+" + added + "\n tail\n")
		if err != nil {
			t.Fatal(err)
		}
		return files
	}
	if !sameChanges(patch("ctx", "new"), patch("moved context", "new")) {
		t.Error("a patch whose only difference is its context lines must count as unchanged")
	}
	if sameChanges(patch("ctx", "new"), patch("ctx", "newer")) {
		t.Error("an edited added line must count as changed")
	}
}

func TestReviewerCount(t *testing.T) {
	t.Parallel()
	tests := []struct{ l, f, want int }{
		{0, 0, 0},
		{99, 30, 1}, {100, 1, 1}, {100, 2, 1}, {100, 3, 2}, {499, 30, 2},
		{500, 3, 1}, {500, 9, 3}, {500, 30, 4}, {1999, 30, 4},
		{2000, 13, 7}, {2000, 30, 8}, {4999, 30, 8},
		{5000, 10, 10}, {5000, 30, 16},
	}
	for _, tt := range tests {
		if got := reviewerCount(tt.l, tt.f); got != tt.want {
			t.Errorf("reviewerCount(L=%d, F=%d) = %d, want %d", tt.l, tt.f, got, tt.want)
		}
	}
}

func TestIsSmall(t *testing.T) {
	t.Parallel()
	file := func(path string, lines int) fileDiff { return fileDiff{Path: path, Added: lines} }
	tests := []struct {
		name  string
		files []fileDiff
		want  bool
	}{
		{"no files", nil, true},
		{"two files under 100 lines", []fileDiff{file("a.go", 50), file("b.go", 49)}, true},
		{"100 lines", []fileDiff{file("a.go", 50), file("b.go", 50)}, false},
		{"three files", []fileDiff{file("a", 1), file("b", 1), file("c", 1)}, false},
		{"excluded files count", []fileDiff{file("a.go", 60), file("go.sum", 40)}, false},
		{"protected path", []fileDiff{file("internal/smu/write.go", 1)}, false},
		{"protected nix", []fileDiff{file("nix/module.nix", 1)}, false},
		{"protected rename source", []fileDiff{{Path: "docs/x.go", OldPath: "internal/journal/x.go", Added: 1}}, false},
		{"lookalike path", []fileDiff{file("internal/smuggle/x.go", 1)}, true},
	}
	for _, tt := range tests {
		if got := isSmall(tt.files); got != tt.want {
			t.Errorf("%s: isSmall = %t, want %t", tt.name, got, tt.want)
		}
	}
}

// pullHandler answers pr view with the given heads in turn and pr diff with diff.
func pullHandler(t *testing.T, diff string, heads ...string) func([]string) ([]byte, error) {
	t.Helper()
	views := 0
	return func(args []string) ([]byte, error) {
		switch {
		case args[0] == "pr" && args[1] == "view":
			head := heads[min(views, len(heads)-1)]
			views++
			return fmt.Appendf(nil, `{"headRefOid":%q,"baseRefOid":%q,"url":%q}`, head, baseSHA, prURL), nil
		case args[0] == "pr" && args[1] == "diff":
			if diff == "ERROR" {
				return nil, errors.New("gh pr diff: HTTP 502")
			}
			return []byte(diff), nil
		}
		return nil, fmt.Errorf("unexpected gh %v", args)
	}
}

func snapshotDir(tl tools) string {
	return filepath.Join(tl.tmp, "togi-review", "700-"+headSHA[:8])
}

func TestSnapshotFirstReview(t *testing.T) {
	t.Parallel()
	tl, g, _, out, _ := testTools(t, pullHandler(t, samplePR, headSHA, headSHA), nil)
	if err := runSnapshot(tl, []string{"700"}); err != nil {
		t.Fatal(err)
	}
	dir := snapshotDir(tl)
	if got := readFile(t, filepath.Join(dir, "pr.diff")); got != samplePR {
		t.Error("pr.diff is not the frozen diff byte for byte")
	}
	checkGolden(t, "snapshot/manifest.golden", readFile(t, filepath.Join(dir, "manifest.json")))
	checkGolden(t, "snapshot/summary.golden", strings.ReplaceAll(out.String(), dir, "<dir>"))
	// Hunk files: included files only, named by position in the manifest.
	var m manifest
	if err := json.Unmarshal([]byte(readFile(t, filepath.Join(dir, "manifest.json"))), &m); err != nil {
		t.Fatal(err)
	}
	var onDisk []string
	entries, err := os.ReadDir(filepath.Join(dir, "files"))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		onDisk = append(onDisk, "files/"+e.Name())
	}
	var named []string
	for _, f := range m.included() {
		named = append(named, f.HunkFile)
		if got := readFile(t, filepath.Join(dir, f.HunkFile)); !strings.HasPrefix(got, "diff --git ") || !strings.Contains(samplePR, got) {
			t.Errorf("%s is not %s's section of the diff", f.HunkFile, f.Path)
		}
	}
	if diff := cmp.Diff(named, onDisk); diff != "" {
		t.Errorf("hunk files named in the manifest vs written (-named +written):\n%s", diff)
	}
	if _, err := os.Stat(filepath.Join(dir, "delta.diff")); err == nil {
		t.Error("a first review wrote delta.diff")
	}
	wantCalls := []string{"gh pr view 700 --json headRefOid,baseRefOid,url", "gh pr diff 700 --color=never --allow-escape-sequences", "gh pr view 700 --json headRefOid,baseRefOid,url"}
	if diff := cmp.Diff(wantCalls, g.joined()); diff != "" {
		t.Errorf("gh calls (-want +got):\n%s", diff)
	}
}

func TestSnapshotRefusesMovedHead(t *testing.T) {
	t.Parallel()
	tl, _, _, _, _ := testTools(t, pullHandler(t, samplePR, headSHA, movedSHA), nil)
	err := runSnapshot(tl, []string{"700"})
	if err == nil || !strings.Contains(err.Error(), "moved while the snapshot ran") {
		t.Fatalf("error = %v, want a moved-head refusal", err)
	}
	if _, statErr := os.Stat(filepath.Join(tl.tmp, "togi-review")); statErr == nil {
		t.Error("a refused snapshot left a directory behind")
	}
}

func TestSnapshotDiffFailure(t *testing.T) {
	t.Parallel()
	tl, _, _, _, _ := testTools(t, pullHandler(t, "ERROR", headSHA), nil)
	if err := runSnapshot(tl, []string{"700"}); err == nil || !strings.Contains(err.Error(), "HTTP 502") {
		t.Fatalf("error = %v, want the gh failure", err)
	}
	tl, _, _, _, _ = testTools(t, pullHandler(t, "GraphQL: oops\n", headSHA), nil)
	if err := runSnapshot(tl, []string{"700"}); err == nil || !strings.Contains(err.Error(), "not a unified diff") {
		t.Fatalf("error = %v, want a refusal to take text for a diff", err)
	}
}

func TestSnapshotUsage(t *testing.T) {
	t.Parallel()
	tl, _, _, _, _ := testTools(t, nil, nil)
	for _, args := range [][]string{nil, {"1", "2"}, {"some-dir"}, {"--previous", previousURL, "--cover", "-", "some-dir"}} {
		if err := runSnapshot(tl, args); err == nil || !strings.Contains(err.Error(), "usage: reviews snapshot") {
			t.Errorf("snapshot %v: error = %v, want usage", args, err)
		}
	}
}

// reReviewTools fakes a pull request that moved from oldHeadSHA to headSHA with the previous record's body.
func reReviewTools(t *testing.T, recordBody string, rangeDiff string, patches map[string]string) (tools, *fakeRunner) {
	t.Helper()
	pr := pullHandler(t, samplePR, headSHA)
	gh := func(args []string) ([]byte, error) {
		if args[0] == "api" {
			if args[1] != "repos/shgew/togi/issues/comments/4242" {
				return nil, fmt.Errorf("unexpected api %v", args)
			}
			b, _ := json.Marshal(map[string]any{"body": recordBody, "user": map[string]string{"login": "robotogi[bot]"}})
			return b, nil
		}
		return pr(args)
	}
	git := func(args []string) ([]byte, error) {
		switch args[0] {
		case "fetch":
			return nil, nil
		case "range-diff":
			return []byte(rangeDiff), nil
		case "diff":
			key := args[len(args)-2] + " " + args[len(args)-1]
			if p, ok := patches[key]; ok {
				return []byte(p), nil
			}
		}
		return nil, fmt.Errorf("unexpected git %v", args)
	}
	tl, _, c, _, _ := testTools(t, gh, git)
	return tl, c
}

func previousBody(version int, base string) string {
	b := fmt.Sprintf(`{"version":%d,"head_sha":%q,"findings":[]`, version, oldHeadSHA)
	if base != "" {
		b += fmt.Sprintf(`,"base_sha":%q`, base)
	}
	return "## Review record\n\n<!-- togi-review " + b + "} -->\n"
}

func onePatch(file, context, added string) string {
	return "diff --git a/" + file + " b/" + file + "\n--- a/" + file + "\n+++ b/" + file + "\n@@ -5,3 +5,3 @@\n " + context + "\n-old\n+" + added + "\n tail\n"
}

func TestSnapshotReReviewClassifiesPatches(t *testing.T) {
	t.Parallel()
	rangeDiff := `1:  aaa1111 = 1:  bbb1111 stays the same
2:  aaa2222 ! 2:  bbb2222 only context moved
3:  aaa3333 ! 3:  bbb3333 edited added line
-:  ------- > 4:  bbb4444 new commit
4:  aaa5555 < -:  ------- dropped commit
`
	patches := map[string]string{
		"aaa2222^ aaa2222": onePatch("a.go", "before", "x"),
		"bbb2222^ bbb2222": onePatch("a.go", "other context", "x"),
		"aaa3333^ aaa3333": onePatch("b.go", "ctx", "v1"),
		"bbb3333^ bbb3333": onePatch("b.go", "ctx", "v2"),
		"bbb4444^ bbb4444": onePatch("c.go", "ctx", "fresh"),
		"aaa5555 aaa5555^": onePatch("d.go", "ctx", "gone"),
	}
	tl, git := reReviewTools(t, previousBody(3, oldBaseSHA), rangeDiff, patches)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	dir := snapshotDir(tl)
	var m manifest
	if err := json.Unmarshal([]byte(readFile(t, filepath.Join(dir, "manifest.json"))), &m); err != nil {
		t.Fatal(err)
	}
	want := []patchStatus{
		{Old: "aaa1111", New: "bbb1111", Subject: "stays the same", Status: "unchanged"},
		{Old: "aaa2222", New: "bbb2222", Subject: "only context moved", Status: "unchanged", ContextOnly: true},
		{Old: "aaa3333", New: "bbb3333", Subject: "edited added line", Status: "changed"},
		{New: "bbb4444", Subject: "new commit", Status: "added"},
		{Old: "aaa5555", Subject: "dropped commit", Status: "removed"},
	}
	if diff := cmp.Diff(want, m.Patches); diff != "" {
		t.Errorf("patches (-want +got):\n%s", diff)
	}
	if m.CarryForward {
		t.Error("a delta with changed, added and removed patches carried forward")
	}
	var paths []string
	for _, f := range m.Files {
		paths = append(paths, f.Path)
	}
	// The context-only and unchanged patches are not in the delta; the others are.
	if diff := cmp.Diff([]string{"b.go", "c.go", "d.go"}, paths); diff != "" {
		t.Errorf("delta files (-want +got):\n%s", diff)
	}
	delta := readFile(t, filepath.Join(dir, "delta.diff"))
	wantDelta := onePatch("b.go", "ctx", "v2") + onePatch("c.go", "ctx", "fresh") + onePatch("d.go", "ctx", "gone")
	if delta != wantDelta {
		t.Errorf("delta.diff = %q, want %q", delta, wantDelta)
	}
	if got := readFile(t, filepath.Join(dir, "pr.diff")); got != samplePR {
		t.Error("pr.diff must stay the whole frozen diff on a re-review")
	}
	if m.Small || m.PRFiles != 8 {
		t.Errorf("small = %t over %d files: the rule must measure the whole diff, not the delta", m.Small, m.PRFiles)
	}
	wantFetch := "git fetch --quiet origin " + oldBaseSHA + " " + oldHeadSHA + " " + baseSHA + " " + headSHA
	if got := git.joined()[0]; got != wantFetch {
		t.Errorf("first git call = %q, want %q", got, wantFetch)
	}
	if m.Previous == nil || m.Previous.URL != previousURL || m.Previous.HeadSHA != oldHeadSHA || m.Previous.BaseSHA != oldBaseSHA {
		t.Errorf("previous = %+v", m.Previous)
	}
}

func TestSnapshotReReviewCarryForward(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 = 1:  bbb1111 one\n2:  aaa2222 ! 2:  bbb2222 context only\n"
	patches := map[string]string{
		"aaa2222^ aaa2222": onePatch("a.go", "before", "x"),
		"bbb2222^ bbb2222": onePatch("a.go", "after", "x"),
	}
	tl, _ := reReviewTools(t, previousBody(3, oldBaseSHA), rangeDiff, patches)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(snapshotDir(tl))
	if err != nil {
		t.Fatal(err)
	}
	if !m.CarryForward || len(m.Files) != 0 || m.Reviewers != 0 {
		t.Errorf("carry forward = %t, files = %d, reviewers = %d; want a carried-forward manifest with nothing to review", m.CarryForward, len(m.Files), m.Reviewers)
	}
}

func TestSnapshotReReviewFallback(t *testing.T) {
	t.Parallel()
	tl, git := reReviewTools(t, previousBody(1, ""), "", nil)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	dir := snapshotDir(tl)
	m, err := readManifest(dir)
	if err != nil {
		t.Fatal(err)
	}
	if m.Fallback == "" || m.Previous == nil || m.Previous.BaseSHA != "" || len(m.Patches) != 0 {
		t.Errorf("manifest = %+v, want a fallback naming the previous record and no patches", m)
	}
	if len(m.Files) != 8 {
		t.Errorf("fallback covers %d files, want the whole layer's 8", len(m.Files))
	}
	if _, err := os.Stat(filepath.Join(dir, "delta.diff")); err == nil {
		t.Error("a fallback wrote delta.diff")
	}
	if len(git.calls) != 0 {
		t.Errorf("a fallback ran git: %v", git.joined())
	}
}

func TestSnapshotRejectsPrevious(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name, url, body, login, want string
	}{
		{"other pull request", "https://github.com/shgew/togi/pull/9#issuecomment-4242", previousBody(3, oldBaseSHA), "robotogi[bot]", "not on pull request #700"},
		{"not a comment URL", "https://github.com/shgew/togi/pull/700", previousBody(3, oldBaseSHA), "robotogi[bot]", "not a pull request comment URL"},
		{"someone else's comment", previousURL, previousBody(3, oldBaseSHA), "shgew", "not robotogi"},
		{"no record", previousURL, "just a comment", "robotogi[bot]", "no togi-review block"},
		{"already on this head", previousURL, strings.ReplaceAll(previousBody(3, oldBaseSHA), oldHeadSHA, headSHA), "robotogi[bot]", "already covers this head"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			pr := pullHandler(t, samplePR, headSHA)
			gh := func(args []string) ([]byte, error) {
				if args[0] == "api" {
					b, _ := json.Marshal(map[string]any{"body": tt.body, "user": map[string]string{"login": tt.login}})
					return b, nil
				}
				return pr(args)
			}
			tl, _, _, _, _ := testTools(t, gh, nil)
			err := runSnapshot(tl, []string{"--previous", tt.url, "700"})
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("error = %v, want one containing %q", err, tt.want)
			}
		})
	}
}

func TestParseRangeDiff(t *testing.T) {
	t.Parallel()
	got, err := parseRangeDiff(" 1:  abc1234 = 12:  def5678 Subject with = and ! signs\n-:  ------- > 13:  0123abc added\n")
	if err != nil {
		t.Fatal(err)
	}
	want := []rangeDiffEntry{
		{Old: "abc1234", New: "def5678", Mark: '=', Subject: "Subject with = and ! signs"},
		{New: "0123abc", Mark: '>', Subject: "added"},
	}
	if diff := cmp.Diff(want, got, cmp.AllowUnexported(rangeDiffEntry{})); diff != "" {
		t.Errorf("entries (-want +got):\n%s", diff)
	}
	if _, err := parseRangeDiff("fatal: bad revision\n"); err == nil {
		t.Error("an error message parsed as range-diff output")
	}
}

func TestParseCover(t *testing.T) {
	t.Parallel()
	ranges, unbuilt, err := parseCover(`internal/a.go:10-12
internal/a.go:30
Every changed Go line the profile measures ran in a test since main.
b_linux.go: not built for darwin/arm64
`)
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff([]coverRange{{"internal/a.go", 10, 12}, {"internal/a.go", 30, 30}}, ranges); diff != "" {
		t.Errorf("ranges (-want +got):\n%s", diff)
	}
	if diff := cmp.Diff([]notBuilt{{"b_linux.go", "darwin/arm64"}}, unbuilt); diff != "" {
		t.Errorf("not built (-want +got):\n%s", diff)
	}
	if _, _, err := parseCover("a.go:9-3\n"); err == nil {
		t.Error("a backwards range was accepted")
	}
}

func TestIntersectCover(t *testing.T) {
	t.Parallel()
	hunks := map[string][]span{"a.go": {{10, 20}, {40, 45}}, "b.go": {{1, 2}}}
	ranges := []coverRange{
		{"a.go", 5, 12},  // clipped at the start of a hunk
		{"a.go", 15, 16}, // inside
		{"a.go", 21, 39}, // between hunks: dropped
		{"a.go", 18, 42}, // spans both hunks
		{"c.go", 1, 9},   // file outside the record: dropped
		{"a.go", 15, 16}, // duplicate
	}
	got := intersectCover(ranges, []notBuilt{{"b.go", "darwin/arm64"}, {"c.go", "darwin/arm64"}}, hunks)
	want := coverage{
		Reported: 6,
		Ranges:   []coverRange{{"a.go", 10, 12}, {"a.go", 15, 16}, {"a.go", 18, 20}, {"a.go", 40, 42}},
		NotBuilt: []notBuilt{{"b.go", "darwin/arm64"}},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("coverage (-want +got):\n%s", diff)
	}
}

// TestSnapshotCoverFollowsHunks drops ranges outside the frozen hunks, and takes coverage that arrives after the snapshot.
func TestSnapshotCoverFollowsHunks(t *testing.T) {
	t.Parallel()
	cover := "cmd/togi/main.go:11\ncmd/togi/main.go:12-20\ncmd/togi/main.go:41-42\ngo.sum:2\ninternal/old.go:1\n"
	coverFile := filepath.Join(t.TempDir(), "cover.txt")
	if err := os.WriteFile(coverFile, []byte(cover), 0o644); err != nil {
		t.Fatal(err)
	}
	tl, _, _, out, _ := testTools(t, pullHandler(t, samplePR, headSHA), nil)
	if err := runSnapshot(tl, []string{"700"}); err != nil {
		t.Fatal(err)
	}
	dir := snapshotDir(tl)
	if m, _ := readManifest(dir); m.Coverage != nil {
		t.Fatal("coverage appeared without cover output")
	}
	out.Reset()
	if err := runSnapshot(tl, []string{"--cover", coverFile, dir}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(dir)
	if err != nil {
		t.Fatal(err)
	}
	// 12-20 is clipped to line 12 and 41-42 to 42; lines outside the hunks, go.sum and the deleted file are dropped.
	if diff := cmp.Diff([]coverRange{{"cmd/togi/main.go", 11, 11}, {"cmd/togi/main.go", 12, 12}, {"cmd/togi/main.go", 42, 42}}, m.Coverage.Ranges); diff != "" {
		t.Errorf("ranges (-want +got):\n%s", diff)
	}
	if m.Coverage.Reported != 5 {
		t.Errorf("reported = %d, want 5", m.Coverage.Reported)
	}
	if !strings.Contains(out.String(), "uncovered: 3 of 5 reported ranges inside the hunks") {
		t.Errorf("summary = %q", out.String())
	}
}

func TestSnapshotCoverOnDeltaHunks(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 ! 1:  bbb1111 edited\n"
	patches := map[string]string{
		"aaa1111^ aaa1111": onePatch("a.go", "ctx", "v1"),
		"bbb1111^ bbb1111": onePatch("a.go", "ctx", "v2"),
	}
	tl, _ := reReviewTools(t, previousBody(3, oldBaseSHA), rangeDiff, patches)
	coverFile := filepath.Join(t.TempDir(), "cover.txt")
	// The patch adds line 6 of a.go; line 30 belongs to an inherited change outside the delta.
	if err := os.WriteFile(coverFile, []byte("a.go:6\na.go:30\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := runSnapshot(tl, []string{"--previous", previousURL, "--cover", coverFile, "700"}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(snapshotDir(tl))
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff([]coverRange{{"a.go", 6, 6}}, m.Coverage.Ranges); diff != "" {
		t.Errorf("ranges (-want +got):\n%s", diff)
	}
}
