package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

const generatedMarker = "// Code generated by tool; DO NOT EDIT.\n"

func TestParseDiffQuotedHeaderOnly(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name, in, wantPath, wantStatus, wantExclusion string
		wantBinary                                    bool
	}{
		{
			name: "binary file", wantPath: "café.png", wantStatus: "added", wantBinary: true, wantExclusion: "binary",
			in: "diff --git \"a/caf\\303\\251.png\" \"b/caf\\303\\251.png\"\nnew file mode 100644\nindex 0000000..8888888\nBinary files /dev/null and \"b/caf\\303\\251.png\" differ\n",
		},
		{
			name: "binary patch", wantPath: "café.png", wantStatus: "modified", wantBinary: true, wantExclusion: "binary",
			in: "diff --git \"a/caf\\303\\251.png\" \"b/caf\\303\\251.png\"\nindex 1111111..2222222 100644\nGIT binary patch\nliteral 1\nIcmZ\n\nliteral 0\nHcmV?d00001\n\n",
		},
		{
			name: "empty file with a control character", wantPath: "a\tb", wantStatus: "added",
			in: "diff --git \"a/a\\tb\" \"b/a\\tb\"\nnew file mode 100644\nindex 0000000..e69de29\n",
		},
		{
			name: "mode change", wantPath: "süß.sh", wantStatus: "modified",
			in: "diff --git \"a/s\\303\\274\\303\\237.sh\" \"b/s\\303\\274\\303\\237.sh\"\nold mode 100644\nnew mode 100755\n",
		},
		{
			name: "deleted empty file with a quote", wantPath: `say "hi"`, wantStatus: "deleted",
			in: "diff --git \"a/say \\\"hi\\\"\" \"b/say \\\"hi\\\"\"\ndeleted file mode 100644\nindex e69de29..0000000\n",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			files, err := parseDiff(tt.in)
			if err != nil {
				t.Fatal(err)
			}
			if len(files) != 1 {
				t.Fatalf("got %d files, want 1", len(files))
			}
			f := files[0]
			if f.Path != tt.wantPath || f.Status != tt.wantStatus || f.Binary != tt.wantBinary || excludedReason(f) != tt.wantExclusion {
				t.Errorf("file = path %q, status %q, binary %t, exclusion %q; want %q, %q, %t, %q", f.Path, f.Status, f.Binary, excludedReason(f), tt.wantPath, tt.wantStatus, tt.wantBinary, tt.wantExclusion)
			}
		})
	}
	for _, bad := range []string{
		"diff --git \"a/x\" \"b/y\"\nindex 1..2\n",
		"diff --git \"a/x\" b/x\nindex 1..2\n",
		"diff --git \"a/unterminated b/unterminated\nindex 1..2\n",
	} {
		if _, err := parseDiff(bad); err == nil || !strings.Contains(err.Error(), "cannot read the path") {
			t.Errorf("parseDiff(%q) error = %v, want a path refusal", bad, err)
		}
	}
}

func TestSnapshotRecordsQuotedHeaderOnlyPaths(t *testing.T) {
	t.Parallel()
	diff := "diff --git \"a/caf\\303\\251.png\" \"b/caf\\303\\251.png\"\nnew file mode 100644\nindex 0000000..8888888\nBinary files /dev/null and \"b/caf\\303\\251.png\" differ\n" +
		"diff --git \"a/a\\tb\" \"b/a\\tb\"\nnew file mode 100644\nindex 0000000..e69de29\n" +
		"diff --git \"a/s\\303\\274.sh\" \"b/s\\303\\274.sh\"\nold mode 100644\nnew mode 100755\n"
	tl, _, _, _, _ := testTools(t, pullHandler(t, diff, headSHA), nil)
	if err := runSnapshot(tl, []string{"700"}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(snapshotDir(tl))
	if err != nil {
		t.Fatal(err)
	}
	type row struct{ Path, Status, Exclusion string }
	var got []row
	for _, f := range m.Files {
		got = append(got, row{f.Path, f.Status, f.Exclusion})
	}
	want := []row{{"café.png", "added", "binary"}, {"a\tb", "added", ""}, {"s\u00fc.sh", "modified", ""}}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("files (-want +got):\n%s", diff)
	}
	if got := readFile(t, filepath.Join(snapshotDir(tl), "pr.diff")); got != diff {
		t.Error("pr.diff is not the frozen diff byte for byte")
	}
}

func TestSameChangesMetadata(t *testing.T) {
	t.Parallel()
	parse := func(in string) []fileDiff {
		files, err := parseDiff(in)
		if err != nil {
			t.Fatal(err)
		}
		return files
	}
	hunk := "--- a/f\n+++ b/f\n@@ -5,3 +5,3 @@\n ctx\n-old\n+new\n tail\n"
	exec := parse("diff --git a/f b/f\nold mode 100644\nnew mode 100755\nindex 1..2\n" + hunk)
	plain := parse("diff --git a/f b/f\nindex 3..4 100644\n" + hunk)
	if sameChanges(exec, plain) || sameChanges(plain, exec) {
		t.Error("dropping an executable-bit change counted as context only")
	}
	if !sameChanges(exec, parse("diff --git a/f b/f\nold mode 100644\nnew mode 100755\nindex 5..6\n"+strings.Replace(hunk, "ctx", "moved context", 1))) {
		t.Error("the same mode change with moved context must count as unchanged")
	}
	if sameChanges(parse("diff --git a/f b/f\nold mode 100644\nnew mode 100755\n"), parse("diff --git a/f b/f\nold mode 100644\nnew mode 100644\n")) {
		t.Error("different new modes counted as the same")
	}
	if sameChanges(parse("diff --git a/f b/f\nnew file mode 100644\nindex 0000000..e69de29\n"), parse("diff --git a/f b/f\nnew file mode 100755\nindex 0000000..e69de29\n")) {
		t.Error("an empty file added with a different mode counted as the same")
	}
	noNewline := parse("diff --git a/f b/f\n--- a/f\n+++ b/f\n@@ -1 +1 @@\n-a\n+a\n\\ No newline at end of file\n")
	newline := parse("diff --git a/f b/f\n--- a/f\n+++ b/f\n@@ -1 +1 @@\n-a\n+a\n")
	if sameChanges(noNewline, newline) {
		t.Error("a patch that ends the file without a newline counted as the same as one that does not")
	}
	binary := func(old, new, payload string) []fileDiff {
		return parse("diff --git a/b.bin b/b.bin\nindex " + old + ".." + new + " 100644\nGIT binary patch\n" + payload + "\n")
	}
	if sameChanges(binary("1111111", "2222222", "literal 1"), binary("1111111", "3333333", "literal 1")) {
		t.Error("binary files with different resulting objects counted as the same")
	}
	if !sameChanges(binary("1111111", "2222222", "literal 1"), binary("4444444", "2222222", "delta 1")) {
		t.Error("a binary file with the same resulting object must count as unchanged whatever it was before")
	}
	noIndex := func(payload string) []fileDiff {
		return parse("diff --git a/b.bin b/b.bin\nGIT binary patch\n" + payload + "\n")
	}
	if sameChanges(noIndex("literal 1"), noIndex("literal 2")) || !sameChanges(noIndex("literal 1"), noIndex("literal 1")) {
		t.Error("without an index line binary files must compare by payload")
	}
}

func TestSnapshotModeOnlyChangeIsNotContextOnly(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 ! 1:  bbb1111 script\n"
	modeAndText := "diff --git a/run.sh b/run.sh\nold mode 100644\nnew mode 100755\n--- a/run.sh\n+++ b/run.sh\n@@ -5,3 +5,3 @@\n ctx\n-old\n+new\n tail\n"
	patches := map[string]string{
		"aaa1111^ aaa1111": modeAndText,
		"bbb1111^ bbb1111": onePatch("run.sh", "ctx", "new"),
	}
	tl, _ := reReviewTools(t, previousBody(3, oldBaseSHA), rangeDiff, patches)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(snapshotDir(tl))
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff([]patchStatus{{Old: "aaa1111", New: "bbb1111", Subject: "script", Status: "changed"}}, m.Patches); diff != "" {
		t.Errorf("patches (-want +got):\n%s", diff)
	}
	if m.CarryForward || len(m.Files) != 1 || m.Files[0].Path != "run.sh" {
		t.Errorf("carry forward = %t, files = %+v; want the changed patch re-reviewed", m.CarryForward, m.Files)
	}
}

func TestGeneratedContent(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name, in string
		want     bool
	}{
		{"marker first", generatedMarker + "package p\n", true},
		{"marker after a license comment and a blank line", "// Copyright\n\n" + generatedMarker + "\npackage p\n", true},
		{"windows line ends", "// Code generated by tool; DO NOT EDIT.\r\npackage p\n", true},
		{"marker after the package clause", "package p\n" + generatedMarker, false},
		{"marker mid-sentence", "// see: // Code generated by tool; DO NOT EDIT.\npackage p\n", false},
		{"missing the closing words", "// Code generated by tool\npackage p\n", false},
		{"empty", "", false},
	}
	for _, tt := range tests {
		if got := generatedContent(tt.in); got != tt.want {
			t.Errorf("%s: generatedContent = %t, want %t", tt.name, got, tt.want)
		}
	}
}

// generatedDiff changes four files that are generated or hand-written in ways their sections do not all show.
const generatedDiff = `diff --git a/gen/a.go b/gen/a.go
index 1111111..2222222 100644
--- a/gen/a.go
+++ b/gen/a.go
@@ -20,2 +20,3 @@
 x
+y
 z
diff --git a/gen/hand.go b/gen/hand.go
index 3333333..4444444 100644
--- a/gen/hand.go
+++ b/gen/hand.go
@@ -1,3 +1,2 @@
-// Code generated by tool; DO NOT EDIT.
 package gen
 var a = 1
diff --git a/gen/old.go b/gen/old.go
deleted file mode 100644
index 5555555..0000000
--- a/gen/old.go
+++ /dev/null
@@ -1,2 +0,0 @@
-// Code generated by tool; DO NOT EDIT.
-package gen
diff --git a/gen/ren_old.go b/gen/ren_new.go
similarity index 70%
rename from gen/ren_old.go
rename to gen/ren_new.go
index 6666666..7777777 100644
--- a/gen/ren_old.go
+++ b/gen/ren_new.go
@@ -1,3 +1,3 @@
 // Code generated by tool; DO NOT EDIT.
 package gen
-var a = 1
+var a = 2
`

func TestSnapshotExcludesGeneratedFilesFromTheirContents(t *testing.T) {
	t.Parallel()
	contents := map[string]string{
		"gen/a.go":       generatedMarker + "\npackage gen\n" + strings.Repeat("// line\n", 30),
		"gen/hand.go":    "package gen\nvar a = 1\n",
		"gen/ren_new.go": generatedMarker + "package gen\nvar a = 2\n",
	}
	tl, g, _, _, _ := testTools(t, pullFake(generatedDiff, contents, func(int) pullInfo { return pullInfo{Head: headSHA, Base: baseSHA} }), nil)
	if err := runSnapshot(tl, []string{"700"}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(snapshotDir(tl))
	if err != nil {
		t.Fatal(err)
	}
	type row struct{ Path, Exclusion string }
	var got []row
	for _, f := range m.Files {
		got = append(got, row{f.Path, f.Exclusion})
	}
	want := []row{{"gen/a.go", "generated"}, {"gen/hand.go", ""}, {"gen/old.go", "generated"}, {"gen/ren_new.go", "generated"}}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("exclusions (-want +got):\n%s", diff)
	}
	// Only the hand-written file counts toward F and L: its removed marker line.
	if m.IncludedFiles != 1 || m.IncludedLines != 1 || m.Reviewers != 1 {
		t.Errorf("F = %d, L = %d, reviewers = %d; want 1, 1, 1", m.IncludedFiles, m.IncludedLines, m.Reviewers)
	}
	var reads []string
	for _, c := range g.joined() {
		if strings.HasPrefix(c, "gh api ") {
			reads = append(reads, c)
		}
	}
	prefix := "gh api -H Accept: application/vnd.github.raw+json repos/shgew/togi/contents/"
	wantReads := []string{prefix + "gen/a.go?ref=" + headSHA, prefix + "gen/hand.go?ref=" + headSHA, prefix + "gen/ren_new.go?ref=" + headSHA}
	if diff := cmp.Diff(wantReads, reads); diff != "" {
		t.Errorf("file reads (-want +got; a deleted file's section shows its whole content, so it is not read):\n%s", diff)
	}
}

func TestSnapshotFileReadFailure(t *testing.T) {
	t.Parallel()
	pr := pullHandler(t, generatedDiff, headSHA)
	gh := func(args []string) ([]byte, error) {
		if args[0] == "api" {
			return nil, errors.New("gh api: HTTP 500")
		}
		return pr(args)
	}
	tl, _, _, _, _ := testTools(t, gh, nil)
	err := runSnapshot(tl, []string{"700"})
	if err == nil || !strings.Contains(err.Error(), "read gen/a.go at "+short(headSHA)) || !strings.Contains(err.Error(), "HTTP 500") {
		t.Fatalf("error = %v, want the failed read named, never an included file", err)
	}
}

func TestSnapshotExcludesGeneratedDeltaFile(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 ! 1:  bbb1111 edit\n"
	patches := map[string]string{
		"aaa1111^ aaa1111": onePatch("gen/a.go", "ctx", "v1"),
		"bbb1111^ bbb1111": onePatch("gen/a.go", "ctx", "v2"),
	}
	tl, _ := reReview{
		body: previousBody(3, oldBaseSHA), rangeDiff: rangeDiff, patches: patches,
		contents: map[string]string{"gen/a.go": generatedMarker + "package gen\n"},
	}.tools(t)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	m, err := readManifest(snapshotDir(tl))
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Files) != 1 || m.Files[0].Exclusion != "generated" || m.IncludedFiles != 0 || m.IncludedLines != 0 || m.Reviewers != 0 {
		t.Errorf("manifest = files %+v, F %d, L %d, reviewers %d; want the delta's generated file excluded and not counted", m.Files, m.IncludedFiles, m.IncludedLines, m.Reviewers)
	}
}

func TestSnapshotCarryForwardNeedsSuccess(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 = 1:  bbb1111 one\n"
	tests := []struct {
		name, body            string
		wantCarry             bool
		wantVerdict, wantNote string
	}{
		{name: "success", body: previousBodyVerdict(3, oldBaseSHA, "success"), wantCarry: true, wantVerdict: "success"},
		{name: "blocked", body: previousBodyVerdict(3, oldBaseSHA, "blocked"), wantVerdict: "blocked", wantNote: "the previous record's verdict is blocked, not success"},
		{name: "unknown verdict", body: previousBodyVerdict(3, oldBaseSHA, "pending"), wantVerdict: "pending", wantNote: "the previous record's verdict is pending, not success"},
		{name: "version 2 has no verdict", body: previousBodyVerdict(2, oldBaseSHA, ""), wantNote: "the previous record's verdict is not recorded, not success"},
		{name: "empty verdict", body: previousBodyVerdict(3, oldBaseSHA, ""), wantNote: "the previous record's verdict is not recorded, not success"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			tl, _ := reReviewTools(t, tt.body, rangeDiff, nil)
			if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
				t.Fatal(err)
			}
			m, err := readManifest(snapshotDir(tl))
			if err != nil {
				t.Fatal(err)
			}
			if m.CarryForward != tt.wantCarry {
				t.Errorf("carry forward = %t, want %t", m.CarryForward, tt.wantCarry)
			}
			if m.Previous == nil || m.Previous.Verdict != tt.wantVerdict {
				t.Errorf("previous = %+v, want its verdict %q kept", m.Previous, tt.wantVerdict)
			}
			if m.Fallback != "" || len(m.Files) != 0 || len(m.Patches) != 1 || m.Patches[0].Status != "unchanged" {
				t.Errorf("an unchanged rebase must still be classified and leave nothing to review: fallback %q, files %d, patches %+v", m.Fallback, len(m.Files), m.Patches)
			}
			out := tl.stdout.(*bytes.Buffer).String()
			if got := strings.Contains(out, "carry the record forward"); got != tt.wantCarry {
				t.Errorf("summary says carry forward = %t, want %t:\n%s", got, tt.wantCarry, out)
			}
			if tt.wantNote != "" && !strings.Contains(out, tt.wantNote) {
				t.Errorf("summary lacks %q:\n%s", tt.wantNote, out)
			}
		})
	}
}

func TestSnapshotRefusesMoveAfterRemoteWork(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 ! 1:  bbb1111 edit\n"
	patches := map[string]string{
		"aaa1111^ aaa1111": onePatch("b.go", "ctx", "v1"),
		"bbb1111^ bbb1111": onePatch("b.go", "ctx", "v2"),
	}
	steps := map[string]func(args []string) bool{
		"fetching the previous record": func(args []string) bool { return args[0] == "api" && strings.Contains(args[1], "/issues/comments/") },
		"constructing the delta":       func(args []string) bool { return args[0] == "range-diff" },
		"reading a file at the head":   func(args []string) bool { return args[0] == "api" && strings.Contains(args[len(args)-1], "/contents/") },
	}
	for step, at := range steps {
		for _, side := range []string{"head", "base"} {
			t.Run(step+"/"+side, func(t *testing.T) {
				t.Parallel()
				moved := false
				trip := func(args []string) {
					if at(args) {
						moved = true
					}
				}
				tl, _ := reReview{
					body: previousBody(3, oldBaseSHA), rangeDiff: rangeDiff, patches: patches,
					onAPI: trip, onGit: trip,
					view: func(int) pullInfo {
						p := pullInfo{Head: headSHA, Base: baseSHA}
						switch {
						case moved && side == "head":
							p.Head = movedSHA
						case moved:
							p.Base = movedSHA
						}
						return p
					},
				}.tools(t)
				err := runSnapshot(tl, []string{"--previous", previousURL, "700"})
				if err == nil || !strings.Contains(err.Error(), "moved while the snapshot ran") || !strings.Contains(err.Error(), movedSHA) {
					t.Fatalf("error = %v, want a refusal naming the moved %s", err, side)
				}
				if !moved {
					t.Fatal("the fake never moved the pull request: the step did not run")
				}
				if _, statErr := os.Stat(filepath.Join(tl.tmp, "togi-review")); statErr == nil {
					t.Error("a refused snapshot left a directory behind")
				}
			})
		}
	}
}

func TestSnapshotRefusesMoveWhileReadingFirstReviewFiles(t *testing.T) {
	t.Parallel()
	moved := false
	pr := pullFake(samplePR, sampleContents, func(int) pullInfo {
		if moved {
			return pullInfo{Head: headSHA, Base: movedSHA}
		}
		return pullInfo{Head: headSHA, Base: baseSHA}
	})
	gh := func(args []string) ([]byte, error) {
		if args[0] == "api" {
			moved = true
		}
		return pr(args)
	}
	tl, _, _, _, _ := testTools(t, gh, nil)
	if err := runSnapshot(tl, []string{"700"}); err == nil || !strings.Contains(err.Error(), "moved while the snapshot ran") {
		t.Fatalf("error = %v, want a moved-base refusal", err)
	}
}

func TestSnapshotRemovedPatchInheritedFromNewBase(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 < -:  ------- moved down into the base\n"
	patches := map[string]string{
		"aaa1111 aaa1111^": onePatch("d.go", "ctx", "inherited"),
		// newHead still has everything the commit did to d.go: the base carries it now.
		"aaa1111 -- d.go": "",
	}
	tl, git := reReviewTools(t, previousBody(3, oldBaseSHA), rangeDiff, patches)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	dir := snapshotDir(tl)
	m, err := readManifest(dir)
	if err != nil {
		t.Fatal(err)
	}
	if diff := cmp.Diff([]patchStatus{{Old: "aaa1111", Subject: "moved down into the base", Status: "removed"}}, m.Patches); diff != "" {
		t.Errorf("patches (-want +got):\n%s", diff)
	}
	if len(m.Files) != 0 || m.IncludedFiles != 0 || m.Reviewers != 0 || m.CarryForward {
		t.Errorf("files = %+v, F %d, reviewers %d, carry %t; want a lower-layer change not assigned to this layer as a removal", m.Files, m.IncludedFiles, m.Reviewers, m.CarryForward)
	}
	if got := readFile(t, filepath.Join(dir, "delta.diff")); got != "" {
		t.Errorf("delta.diff = %q, want empty", got)
	}
	want := "git diff --no-color --no-ext-diff -U0 aaa1111 " + headSHA + " -- :(literal)d.go"
	if !slices.Contains(git.joined(), want) {
		t.Errorf("git calls %q lack the effect trace %q", git.joined(), want)
	}
}

func TestSnapshotRemovedPatchKeepsOnlyGoneFiles(t *testing.T) {
	t.Parallel()
	rangeDiff := "1:  aaa1111 < -:  ------- two files\n"
	patches := map[string]string{
		"aaa1111 aaa1111^":   onePatch("kept.go", "ctx", "inherited") + onePatch("gone.go", "ctx", "dropped"),
		"aaa1111 -- kept.go": "",
		"aaa1111 -- gone.go": "diff --git a/gone.go b/gone.go\n--- a/gone.go\n+++ b/gone.go\n@@ -6 +5,0 @@\n-old\n",
	}
	tl, _ := reReviewTools(t, previousBody(3, oldBaseSHA), rangeDiff, patches)
	if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
		t.Fatal(err)
	}
	dir := snapshotDir(tl)
	m, err := readManifest(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(m.Files) != 1 || m.Files[0].Path != "gone.go" {
		t.Errorf("files = %+v, want only the file whose effect is gone", m.Files)
	}
	if got, want := readFile(t, filepath.Join(dir, "delta.diff")), onePatch("gone.go", "ctx", "dropped"); got != want {
		t.Errorf("delta.diff = %q, want %q", got, want)
	}
}

func TestEffectGone(t *testing.T) {
	t.Parallel()
	parse := func(in string) []fileDiff {
		files, err := parseDiff(in)
		if err != nil {
			t.Fatal(err)
		}
		return files
	}
	const head = "diff --git a/f b/f\n--- a/f\n+++ b/f\n"
	// The reversal of a commit that replaced old line 6 "old" by "gone".
	text := parse(onePatch("f", "ctx", "gone"))[0]
	mode := parse("diff --git a/f b/f\nold mode 100755\nnew mode 100644\n")[0]
	binary := parse("diff --git a/f b/f\nindex 1111111..2222222 100644\nBinary files a/f and b/f differ\n")[0]
	tests := []struct {
		name  string
		f     fileDiff
		since []fileDiff
		want  bool
	}{
		{"file identical to the commit's", text, nil, false},
		{"its added line removed", text, parse(head + "@@ -6 +5,0 @@\n-old\n"), true},
		{"its added line rewritten", text, parse(head + "@@ -6 +6 @@\n-old\n+other\n"), true},
		{"unrelated change elsewhere", text, parse(head + "@@ -20 +20 @@\n-x\n+y\n"), false},
		{"insertion next to its line", text, parse(head + "@@ -6,0 +7 @@\n+z\n"), false},
		{"a line it removed comes back", text, parse(head + "@@ -30,0 +31 @@\n+gone\n"), true},
		{"mode changed since", mode, parse("diff --git a/f b/f\nold mode 100755\nnew mode 100644\n"), true},
		{"only content changed since", mode, parse(head + "@@ -20 +20 @@\n-x\n+y\n"), false},
		{"binary differs since", binary, parse("diff --git a/f b/f\nindex 2222222..3333333 100644\nBinary files a/f and b/f differ\n"), true},
		{"binary identical", binary, nil, false},
	}
	for _, tt := range tests {
		if got := effectGone(tt.f, tt.since); got != tt.want {
			t.Errorf("%s: effectGone = %t, want %t", tt.name, got, tt.want)
		}
	}
}

func TestSnapshotPreviousBase(t *testing.T) {
	t.Parallel()
	changed := "1:  aaa1111 ! 1:  bbb1111 edit\n"
	patches := map[string]string{
		"aaa1111^ aaa1111": onePatch("b.go", "ctx", "v1"),
		"bbb1111^ bbb1111": onePatch("b.go", "ctx", "v2"),
	}
	legacy := previousBodyVerdict(2, "", "")
	t.Run("supplied base replaces the fallback", func(t *testing.T) {
		t.Parallel()
		tl, git := reReviewTools(t, legacy, changed, patches)
		if err := runSnapshot(tl, []string{"--previous", previousURL, "--previous-base", oldBaseSHA, "700"}); err != nil {
			t.Fatal(err)
		}
		dir := snapshotDir(tl)
		m, err := readManifest(dir)
		if err != nil {
			t.Fatal(err)
		}
		if m.Fallback != "" || m.Previous == nil || m.Previous.BaseSHA != oldBaseSHA || m.Previous.HeadSHA != oldHeadSHA {
			t.Errorf("manifest = fallback %q, previous %+v; want the supplied base used", m.Fallback, m.Previous)
		}
		calls := git.joined()
		wantFetch := "git fetch --quiet origin " + oldBaseSHA + " " + oldHeadSHA + " " + baseSHA + " " + headSHA
		wantRange := "git range-diff --no-patch --no-color " + oldBaseSHA + ".." + oldHeadSHA + " " + baseSHA + ".." + headSHA
		if len(calls) < 2 || calls[0] != wantFetch || calls[1] != wantRange {
			t.Errorf("git calls = %q, want the fetch and range-diff of both ranges", calls)
		}
		if len(m.Files) != 1 || m.Files[0].Path != "b.go" {
			t.Errorf("files = %+v, want the delta's b.go", m.Files)
		}
		if got := readFile(t, filepath.Join(dir, "delta.diff")); got != onePatch("b.go", "ctx", "v2") {
			t.Errorf("delta.diff = %q", got)
		}
	})
	t.Run("a recovered legacy record without a verdict does not carry forward", func(t *testing.T) {
		t.Parallel()
		tl, _ := reReviewTools(t, legacy, "1:  aaa1111 = 1:  bbb1111 one\n", nil)
		if err := runSnapshot(tl, []string{"--previous", previousURL, "--previous-base", oldBaseSHA, "700"}); err != nil {
			t.Fatal(err)
		}
		m, err := readManifest(snapshotDir(tl))
		if err != nil {
			t.Fatal(err)
		}
		if m.Fallback != "" || m.CarryForward || len(m.Patches) != 1 || m.Patches[0].Status != "unchanged" {
			t.Errorf("manifest = fallback %q, carry %t, patches %+v; want an unchanged delta that is not carried forward", m.Fallback, m.CarryForward, m.Patches)
		}
	})
	for _, version := range []int{1, 2} {
		t.Run(fmt.Sprintf("a recovered version %d record with an explicit success verdict carries forward", version), func(t *testing.T) {
			t.Parallel()
			tl, _ := reReviewTools(t, previousBodyVerdict(version, "", "success"), "1:  aaa1111 = 1:  bbb1111 one\n", nil)
			if err := runSnapshot(tl, []string{"--previous", previousURL, "--previous-base", oldBaseSHA, "700"}); err != nil {
				t.Fatal(err)
			}
			m, err := readManifest(snapshotDir(tl))
			if err != nil {
				t.Fatal(err)
			}
			if m.Fallback != "" || !m.CarryForward || m.Previous == nil || m.Previous.Verdict != "success" || m.Previous.BaseSHA != oldBaseSHA {
				t.Errorf("manifest = fallback %q, carry %t, previous %+v; want carry-forward on the recovered base", m.Fallback, m.CarryForward, m.Previous)
			}
		})
	}

	t.Run("unrecovered base falls back", func(t *testing.T) {
		t.Parallel()
		tl, git := reReviewTools(t, legacy, "", nil)
		if err := runSnapshot(tl, []string{"--previous", previousURL, "700"}); err != nil {
			t.Fatal(err)
		}
		m, err := readManifest(snapshotDir(tl))
		if err != nil {
			t.Fatal(err)
		}
		if m.Fallback == "" || m.Previous == nil || m.Previous.BaseSHA != "" || len(git.calls) != 0 {
			t.Errorf("fallback %q, previous %+v, git calls %v; want the whole layer and no git", m.Fallback, m.Previous, git.joined())
		}
	})
	t.Run("a base the record contradicts", func(t *testing.T) {
		t.Parallel()
		tl, _ := reReviewTools(t, previousBody(3, oldBaseSHA), changed, patches)
		err := runSnapshot(tl, []string{"--previous", previousURL, "--previous-base", strings.Repeat("3", 40), "700"})
		if err == nil || !strings.Contains(err.Error(), "names base "+oldBaseSHA) {
			t.Fatalf("error = %v, want a refusal of the contradicting base", err)
		}
	})
	t.Run("the record's own base is accepted", func(t *testing.T) {
		t.Parallel()
		tl, _ := reReviewTools(t, previousBody(3, oldBaseSHA), changed, patches)
		if err := runSnapshot(tl, []string{"--previous", previousURL, "--previous-base", oldBaseSHA, "700"}); err != nil {
			t.Fatal(err)
		}
	})
	for name, args := range map[string][]string{
		"without --previous": {"--previous-base", oldBaseSHA, "700"},
		"not a full SHA":     {"--previous", previousURL, "--previous-base", "2222222", "700"},
		"upper case":         {"--previous", previousURL, "--previous-base", strings.ToUpper(baseSHA), "700"},
		"for a snapshot dir": {"--previous-base", oldBaseSHA, "--cover", "-", "some-dir"},
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			tl, _, _, _, _ := testTools(t, nil, nil)
			if err := runSnapshot(tl, args); err == nil || !strings.Contains(err.Error(), "usage: reviews snapshot") {
				t.Fatalf("error = %v, want usage", err)
			}
		})
	}
}
