package main

import (
	"bytes"
	"fmt"
	"io"
	"maps"
	"math"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"time"

	"github.com/shgew/togi/internal/journal"
	"github.com/shgew/togi/internal/machine"
	"github.com/shgew/togi/internal/sim"
	"github.com/shgew/togi/tools/modelcheck"
	"github.com/shgew/togi/tools/trialfacts"
)

type sharedVoltageFit func([]trialfacts.Record) (sim.Config, float64)

func generateSharedVoltageAnchor(extract, out string, stdout io.Writer, fitter sharedVoltageFit) error {
	started := time.Now()
	records, err := trialfacts.Read(extract)
	if err != nil {
		return err
	}
	starts, err := decisive(records)
	if err != nil {
		return err
	}
	for _, r := range starts {
		if len(r.Profile) != 16 {
			return fmt.Errorf("shared-voltage in-sample fit requires 16 cores: fact %s:%d has %d", r.Session, r.Seq, len(r.Profile))
		}
	}
	// The machine file fills empty context fields with simulator defaults on
	// load, which would no longer match the facts the model check replayed.
	if c := starts[0].Context; c == nil || c.BIOSVersion == "" || c.Board == "" || c.CPUModel == "" || c.Microcode == "" || c.BoostLimitMHz == 0 {
		return fmt.Errorf("shared-voltage in-sample fit requires BIOS context with every field set for real-fact replay")
	}
	cfg, loss := fitter(starts)
	if cfg.Cores != 16 || cfg.SharedVoltage == nil {
		return fmt.Errorf("shared-voltage fitter returned a machine without the 16-core shared-voltage model")
	}
	cfg.BIOSContext = *starts[0].Context
	absExtract, err := filepath.Abs(extract)
	if err != nil {
		return fmt.Errorf("resolve extract: %w", err)
	}
	absOut, err := filepath.Abs(out)
	if err != nil {
		return fmt.Errorf("resolve output directory: %w", err)
	}
	rel, err := filepath.Rel(absOut, absExtract)
	if err != nil {
		return fmt.Errorf("relativize extract: %w", err)
	}
	cfg.Facts = filepath.ToSlash(rel)
	path := filepath.Join(out, "target-shared-voltage.toml")
	check, err := modelcheck.CheckRecords(path, extract, cfg, records)
	if err != nil {
		return err
	}
	fmt.Fprintln(stdout, "IN-SAMPLE shared-voltage fit; NOT forward-validated. The 2026-10-04 #306 R7 forward bar failed.")
	fmt.Fprintf(stdout, "Shared-voltage candidate (record only): rate=%.17g/s margin_v=%.17g background_rate=%.17g/s\n", cfg.SharedVoltage.Rate, cfg.SharedVoltage.MarginV, cfg.SharedVoltage.BackgroundRate)
	fmt.Fprintln(stdout, "\nModel check (unchanged 99% binomial intervals; full original extract)")
	fmt.Fprintf(stdout, "%s: %s (%d eligible groups; %d idle failures without start exposure)\n", path, check.Status, len(check.Groups), check.IdleFailures)
	for _, g := range check.Groups {
		if g.Flagged {
			fmt.Fprintf(stdout, "  %s %s cores=%v duration=%ds depth=%d n=%d k=%d interval=[%d,%d] mean_p=%.17g\n", g.Class.Regime, g.Class.Workload, g.Class.Cores, g.Class.DurationS, g.Depth, g.N, g.K, g.Interval[0], g.Interval[1], g.MeanP)
		}
	}
	m, err := sim.New(cfg)
	if err != nil {
		return err
	}
	var r7Loss, predicted float64
	var r7Starts, observed int
	for _, r := range starts {
		if r.Class.Regime != machine.R7 {
			continue
		}
		spec := machine.TrialSpec{Regime: r.Class.Regime, Workload: machine.Workload{ID: r.Class.Workload}, Cores: r.Class.Cores, Duration: time.Duration(r.Class.DurationS) * time.Second, Condition: r.Condition}
		p := m.FailureProbability(r.Profile, spec)
		r7Starts++
		predicted += p
		if r.Outcome == journal.OutcomeFailure {
			observed++
			r7Loss -= math.Log(p)
		} else {
			r7Loss -= math.Log1p(-p)
		}
	}
	fmt.Fprintf(stdout, "All starts in-sample (record only): starts=%d raw total in-sample log loss %.17g log_loss/start=%.17g\n", len(starts), loss, loss/float64(len(starts)))
	var r7MeanLoss float64
	if r7Starts > 0 {
		r7MeanLoss = r7Loss / float64(r7Starts)
	}
	fmt.Fprintf(stdout, "R7 in-sample (record only): starts=%d observed=%d predicted=%.17g raw_log_loss=%.17g log_loss/start=%.17g\n", r7Starts, observed, predicted, r7Loss, r7MeanLoss)
	fmt.Fprintln(stdout, "Unsupported y-cruncher R7 thresholds: per core, max of mprime AVX2 and AVX-512; no hardware evidence.")
	if check.Status != "ok" {
		return fmt.Errorf("in-sample shared-voltage fit fails the unchanged model check; anchor not written")
	}
	content := encodeSharedVoltageAnchor(cfg, len(starts), loss)
	if err := os.MkdirAll(out, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write shared-voltage anchor: %w", err)
	}
	fmt.Fprintf(stdout, "Wrote IN-SAMPLE anchor: %s (NOT forward-validated)\n", path)
	fmt.Fprintf(stdout, "Fit elapsed: %s\n", time.Since(started).Round(time.Millisecond))
	return nil
}

func encodeSharedVoltageAnchor(cfg sim.Config, starts int, loss float64) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated by just fit-shared-voltage; do not hand-edit.")
	fmt.Fprintln(&b, "# IN-SAMPLE all-facts shared-voltage anchor; NOT forward-validated.")
	fmt.Fprintln(&b, "# The first candidate failed the 2026-10-04 #306 R7 forward bar: 36.0 predicted / 17 observed (>2x).")
	fmt.Fprintln(&b, "# That check was not blind; a future forward claim needs a new blind session.")
	fmt.Fprintf(&b, "# All decisive starts=%d; raw Bernoulli negative_log_likelihood=%.17g\n", starts, loss)
	fmt.Fprintln(&b, "# Checked against every eligible group of the full original extract before writing.")
	fmt.Fprintln(&b, "# Unsupported y-cruncher R7 thresholds: per-core max of AVX2/AVX-512; no hardware evidence.")
	fmt.Fprintln(&b, "# Real-fact replay is enabled by replay=true on a bench suite scenario, not by a machine key.")
	encodeConfiguration(&b, cfg)
	v := cfg.SharedVoltage
	fmt.Fprintf(&b, "\n[shared_voltage]\nidle_v = %.17g\nmargin_v = %.17g\nrate = %.17g\nbackground_rate = %.17g\npower_limit_w = %.17g\nthermal_limit_w = %.17g\n", v.IdleV, v.MarginV, v.Rate, v.BackgroundRate, v.PowerLimitW, v.ThermalLimitW)
	for _, workload := range slices.Sorted(maps.Keys(v.Workload)) {
		w := v.Workload[workload]
		table := "shared_voltage.workload." + strconv.Quote(workload)
		fmt.Fprintf(&b, "\n[%s]\nreference_mhz = %.17g\nfull_mhz = [%.17g, %.17g]\nidle_gain_mhz = %.17g\nwatts_per_core = %.17g\noffset_watts_per_count = %.17g\npackage_mhz_per_w = %.17g\nbalance_mhz_per_w = %.17g\n", table, w.ReferenceMHz, w.FullMHz[0], w.FullMHz[1], w.IdleGainMHz, w.WattsPerCore, w.OffsetWattsPerCount, w.PackageMHzPerW, w.BalanceMHzPerW)
		for _, c := range w.Core {
			fmt.Fprintf(&b, "\n[[%s.core]]\nbase_v = %.17g\nthreshold_v = %.17g\ncount_v = %.17g\nclock_v_per_100mhz = %.17g\nthreshold_clock_v_per_100mhz = %.17g\n", table, c.BaseV, c.ThresholdV, c.CountV, c.ClockVPer100MHz, c.ThresholdClockVPer100MHz)
			if c.Signals != nil {
				fmt.Fprint(&b, "signals = {")
				separator := ""
				for _, signal := range slices.Sorted(maps.Keys(c.Signals)) {
					fmt.Fprintf(&b, "%s%s = %.17g", separator, strconv.Quote(string(signal)), c.Signals[signal])
					separator = ", "
				}
				fmt.Fprintln(&b, "}")
			}
		}
	}
	return b.Bytes()
}
