package main

import (
	"fmt"

	"github.com/shgew/togi/internal/sim"
	"github.com/shgew/togi/tools/modelcheck"
)

func groupNote(prefix string, group modelcheck.Group) string {
	return fmt.Sprintf("%s: %s %s cores=%v duration=%ds depth=%d n=%d k=%d", prefix, group.Class.Regime, group.Class.Workload, group.Class.Cores, group.Class.DurationS, group.Depth, group.N, group.K)
}

func encodeMachine(cfg sim.Config, index int, seed uint64, trials int, loss float64, constrained, flagged []modelcheck.Group) ([]byte, error) {
	notes := []string{
		"Generated by just fit",
		fmt.Sprintf("Whole-trial bootstrap: index=%d (0=all facts), seed=%d, trials=%d, negative_log_likelihood=%.9g", index, seed, trials, loss),
		signalsNote(cfg.Model),
	}
	for _, group := range constrained {
		notes = append(notes, groupNote("Constrained bootstrap", group))
	}
	if len(flagged) == 0 {
		notes = append(notes, "Model check against the original extract: ok, no flagged groups.")
	} else {
		notes = append(notes, "Model check against the original extract: flagged.")
	}
	for _, group := range flagged {
		notes = append(notes, fmt.Sprintf("%s interval=[%d,%d]", groupNote("Flagged", group), group.Interval[0], group.Interval[1]))
	}
	return sim.EncodeMachine(cfg, notes...)
}

func encodeSharedVoltageAnchor(cfg sim.Config, trials int, loss float64) ([]byte, error) {
	notes := []string{
		"Generated by just fit-shared-voltage",
		"IN-SAMPLE all-facts shared-voltage anchor; NOT forward-validated.",
		"The first candidate failed the 2026-10-04 #306 R7 forward bar: 36.0 predicted / 17 observed (>2x).",
		"That check was not blind; a future forward claim needs a new blind session.",
		fmt.Sprintf("All decisive trials=%d; raw Bernoulli negative_log_likelihood=%.17g", trials, loss),
		"Checked against every eligible group of the full original extract before writing.",
		signalsNote(cfg.Model),
	}
	return sim.EncodeMachine(cfg, notes...)
}
