package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"io"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"time"

	"github.com/shgew/togi/internal/machine"
	"github.com/shgew/togi/internal/sim"
	"github.com/shgew/togi/tools/modelcheck"
	"github.com/shgew/togi/tools/trialfacts"
)

func main() { os.Exit(run(os.Args[1:], os.Stdout, os.Stderr)) }

func run(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("fit", flag.ContinueOnError)
	flags.SetOutput(stderr)
	extract := flags.String("facts", "tools/bench/facts/target.jsonl.gz", "compressed decisive-facts extract")
	out := flags.String("out", "tools/bench/machines", "output directory for target-fit-0.toml and bootstrap refits")
	seed := flags.Uint64("seed", 263, "fixed bootstrap seed")
	refits := flags.Int("bootstrap", 8, "number of whole-trial bootstrap refits")
	forwardOnly := flags.Bool("forward-only", false, "run only the forward-chained check: fit no ensemble and write no machine files")
	seal := flags.Int("seal", 0, "with --forward-only, leave the newest N sessions out of the forward-chained check")
	if err := flags.Parse(args); errors.Is(err, flag.ErrHelp) {
		return 0
	} else if err != nil {
		return 2
	}
	if flags.NArg() != 0 || *refits < 0 || *seal < 0 || (*seal > 0 && !*forwardOnly) {
		fmt.Fprintln(stderr, "fit: require no positional arguments, a nonnegative --bootstrap, and a nonnegative --seal only with --forward-only")
		return 2
	}
	var err error
	if *forwardOnly {
		err = forward(*extract, *seal, stdout)
	} else {
		err = generate(*extract, *out, *seed, *refits, stdout)
	}
	if err != nil {
		fmt.Fprintf(stderr, "fit: %v\n", err)
		return 1
	}
	return 0
}

func generate(extract, out string, seed uint64, refits int, stdout io.Writer) error {
	started := time.Now()
	records, err := trialfacts.Read(extract)
	if err != nil {
		return err
	}
	starts, err := decisive(records)
	if err != nil {
		return err
	}
	absExtract, err := filepath.Abs(extract)
	if err != nil {
		return fmt.Errorf("resolve extract: %w", err)
	}
	absOut, err := filepath.Abs(out)
	if err != nil {
		return fmt.Errorf("resolve output directory: %w", err)
	}
	rel, err := filepath.Rel(absOut, absExtract)
	if err != nil {
		return fmt.Errorf("relativize extract: %w", err)
	}
	if err := os.MkdirAll(out, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}
	var checks []*modelcheck.Result
	var checker *modelcheck.Checker
	var base sim.Config
	for n := range refits + 1 {
		sample := starts
		if n > 0 {
			sample = bootstrap(starts, seed+uint64(n))
		}
		cfg, loss := fit(sample)
		path := filepath.Join(out, fmt.Sprintf("target-fit-%d.toml", n))
		if checker == nil {
			checker, err = modelcheck.NewChecker(cfg, records)
			if err != nil {
				return err
			}
			base = cloneMachine(cfg)
		}
		m, err := sim.New(cfg)
		if err != nil {
			return err
		}
		unconstrained := checker.Check(path, extract, m)
		var constrained []modelcheck.Group
		if n > 0 && unconstrained.Status == "flagged" {
			for _, group := range unconstrained.Groups {
				if group.Flagged {
					constrained = append(constrained, group)
					fmt.Fprintf(stdout, "Refit %d constraint: %s %s cores=%v duration=%ds depth=%d n=%d k=%d unconstrained_interval=%v mean_p=%.6g\n", n, group.Class.Regime, group.Class.Workload, group.Class.Cores, group.Class.DurationS, group.Depth, group.N, group.K, group.Interval, group.MeanP)
				}
			}
			baseMachine, err := sim.New(base)
			if err != nil {
				return err
			}
			if !checker.Accepts(baseMachine) {
				return fmt.Errorf("all-facts fit fails the unchanged model check; cannot seed constrained refits")
			}
			cfg, loss = fitFrom(sample, &base, checker)
		}
		cfg.Facts = filepath.ToSlash(rel)
		content := encodeMachine(cfg, n, seed, len(sample), loss, constrained)
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return fmt.Errorf("write fitted machine: %w", err)
		}
		loaded, err := sim.LoadMachine(path)
		if err != nil {
			return err
		}
		m, err = sim.New(loaded)
		if err != nil {
			return err
		}
		check := checker.Check(path, extract, m)
		checks = append(checks, check)
		fmt.Fprintf(stdout, "%s: %d starts; negative log likelihood %.6f\n", path, len(sample), loss)
		for j, joint := range cfg.Joints {
			ccd := 0
			for core := range cfg.Cores {
				if _, ok := joint.Members[core]; ok {
					ccd = core / (cfg.Cores / 2)
					break
				}
			}
			fmt.Fprintf(stdout, "  CCD%d joint%d: members=%v rate=%.9g/s after=%.9gs\n", ccd, j, joint.Members, joint.Rate, joint.AfterS)
		}
	}
	modelcheck.Report(stdout, checks)
	if err := reportForwardCheck(stdout, starts, 0); err != nil {
		return err
	}
	fmt.Fprintf(stdout, "Fit elapsed: %s\n", time.Since(started).Round(time.Millisecond))
	return nil
}

func encodeMachine(cfg sim.Config, index int, seed uint64, starts int, loss float64, constrained []modelcheck.Group) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "# Generated by just fit; do not hand-edit.")
	fmt.Fprintf(&b, "# Whole-trial bootstrap: index=%d (0=all facts), seed=%d, starts=%d, negative_log_likelihood=%.9g\n", index, seed, starts, loss)
	fmt.Fprintln(&b, "# Fitted: isolated/resident regime edges, shared rate/growth/near hazard, per-core flat hazard,")
	fmt.Fprintln(&b, "# supported workload overrides, idle edges, and layered R7 CCD joints.")
	fmt.Fprintln(&b, "# Unsupported edges stay -50; unobserved idle exposure cannot identify idle hazards.")
	fmt.Fprintln(&b, "# Fixed: onset boost=0, joint delay=0; default signals/MCE/reset.")
	for _, group := range constrained {
		fmt.Fprintf(&b, "# Constrained bootstrap: %s %s cores=%v duration=%ds depth=%d n=%d k=%d\n", group.Class.Regime, group.Class.Workload, group.Class.Cores, group.Class.DurationS, group.Depth, group.N, group.K)
	}
	fmt.Fprintf(&b, "cores = %d\nfacts = %s\n", cfg.Cores, strconv.Quote(cfg.Facts))
	if cfg.BIOSContext != (machine.BIOSContext{}) {
		c := cfg.BIOSContext
		fmt.Fprintf(&b, "\n[bios_context]\nbios_version = %s\nboard = %s\ncpu_model = %s\nmicrocode = %s\nboost_limit_mhz = %d\n", strconv.Quote(c.BIOSVersion), strconv.Quote(c.Board), strconv.Quote(c.CPUModel), strconv.Quote(c.Microcode), c.BoostLimitMHz)
	}
	m := cfg.Model
	fmt.Fprintf(&b, "\n[model]\npast_edge_rate = %.17g\ngrowth = %.17g\nnear_edge_rate = %.17g\nonset_boost = 0.0\n", m.PastEdgeRate, m.Growth, m.NearEdgeRate)
	if c := cfg.CCD; c != nil {
		fmt.Fprintf(&b, "\n[ccd]\nlog_rate = %.17g\nslope = %.17g\neffect = [%.17g, %.17g]\n", c.LogRate, c.Slope, c.Effect[0], c.Effect[1])
	}
	if s := cfg.SingleCore; s != nil {
		fmt.Fprintf(&b, "\n[single_core]\nlog_rate = %.17g\nslope = %.17g\nresident_effect = %.17g\ncore = [", s.LogRate, s.Slope, s.ResidentEffect)
		for i, effect := range s.Core {
			if i > 0 {
				fmt.Fprint(&b, ", ")
			}
			fmt.Fprintf(&b, "%.17g", effect)
		}
		fmt.Fprintln(&b, "]\nworkload = {")
		for _, workload := range slices.Sorted(maps.Keys(s.Workload)) {
			fmt.Fprintf(&b, "%s = %.17g,\n", strconv.Quote(workload), s.Workload[workload])
		}
		fmt.Fprintln(&b, "}")
	}
	for core, edge := range cfg.Edges {
		fmt.Fprintf(&b, "\n[[core]]\nid = %d\nisolated = [%d, %d, %d, %d, %d]\nresident = [%d, %d, %d, %d, %d, %d, %d]\nflat = %.17g\n", core, edge.Isolated[0], edge.Isolated[1], edge.Isolated[2], edge.Isolated[3], edge.Isolated[4], edge.Resident[0], edge.Resident[1], edge.Resident[2], edge.Resident[3], edge.Resident[4], edge.Resident[5], edge.Resident[6], edge.Flat)
		if edge.Idle != nil {
			fmt.Fprintf(&b, "idle = %d\n", *edge.Idle)
		}
		if len(edge.Workload) > 0 {
			fmt.Fprint(&b, "workload = {")
			separator := ""
			for _, workload := range slices.Sorted(maps.Keys(edge.Workload)) {
				fmt.Fprintf(&b, "%s%s = %d", separator, strconv.Quote(workload), edge.Workload[workload])
				separator = ", "
			}
			fmt.Fprintln(&b, "}")
		}
	}
	for _, joint := range cfg.Joints {
		fmt.Fprintf(&b, "\n[[joint]]\nregimes = [\"R7\"]\nrate = %.17g\nafter_s = 0.0\nsignal = \"crash\"\nmembers = {", joint.Rate)
		separator := ""
		for core := range cfg.Cores {
			if offset, ok := joint.Members[core]; ok {
				fmt.Fprintf(&b, "%s%s = %d", separator, strconv.Quote(strconv.Itoa(core)), offset)
				separator = ", "
			}
		}
		fmt.Fprintln(&b, "}")
	}
	return b.Bytes()
}
