name: check

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/nix
      - name: just check --race
        run: nix develop --command just check --race
      - name: just vuln
        run: nix develop --command just vuln
