name: release

on: workflow_dispatch

permissions:
  contents: write

concurrency:
  group: release

jobs:
  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: github-actions[bot]
      GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      GIT_COMMITTER_NAME: github-actions[bot]
      GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
    steps:
      - uses: actions/checkout@v7
      - name: Give build users KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
      - name: Commit the release
        run: nix develop --command go run ./tools/release -commit
      - name: just check --race
        run: nix develop --command just check --race
      - name: just vuln
        run: nix develop --command just vuln
      - name: Push to main
        run: git push origin HEAD:refs/heads/main
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: nix develop --command go run ./tools/release -publish
